// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Overtime.Data;

#nullable disable

namespace overtime.Migrations
{
    [DbContext(typeof(OvertimeDbContext))]
    [Migration("20260605071821_RemoveEmployeeTableAndRenameBookingStaffId")]
    partial class RemoveEmployeeTableAndRenameBookingStaffId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Time")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Overtime.Data.Entities.BookingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BookingRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("booking_ref");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_phone");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("SlotDate")
                        .HasColumnType("date")
                        .HasColumnName("slot_date");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("BookingRef")
                        .IsUnique();

                    b.HasIndex("StaffId", "SlotDate", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("uq_staff_slot");

                    b.ToTable("bookings", "Time");
                });

            modelBuilder.Entity("Overtime.Data.Entities.LocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("locations", "Time");
                });

            modelBuilder.Entity("Overtime.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<TimeOnly>("ShiftEnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time without time zone")
                        .HasDefaultValue(new TimeOnly(17, 0, 0))
                        .HasColumnName("shift_end");

                    b.Property<TimeOnly>("ShiftStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time without time zone")
                        .HasDefaultValue(new TimeOnly(9, 0, 0))
                        .HasColumnName("shift_start");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<string[]>("WorkDays")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("work_days")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", "Time");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Administrator",
                            FullName = "Administrator",
                            LastName = "",
                            PasswordHash = "AQAAAAIAAYagAAAAEH1t3EW6Mm95tC4JrPTupgiQgLocybyVSjgf5CZGpgUN5ghO+ShIKGHH8fS/MSoU7A==",
                            Role = "admin",
                            ShiftEnd = new TimeOnly(17, 0, 0),
                            ShiftStart = new TimeOnly(9, 0, 0),
                            Username = "admin",
                            WorkDays = new string[0]
                        });
                });

            modelBuilder.Entity("Overtime.Data.Entities.BookingEntity", b =>
                {
                    b.HasOne("Overtime.Data.Entities.UserEntity", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Overtime.Data.Entities.LocationEntity", b =>
                {
                    b.OwnsOne("Overtime.Data.Entities.LocationOpeningHours", "OpeningHours", b1 =>
                        {
                            b1.Property<Guid>("LocationEntityId")
                                .HasColumnType("uuid");

                            b1.HasKey("LocationEntityId");

                            b1.ToTable("locations", "Time");

                            b1.ToJson("opening_hours");

                            b1.WithOwner()
                                .HasForeignKey("LocationEntityId");

                            b1.OwnsOne("Overtime.Data.Entities.OpeningHours", "Friday", b2 =>
                                {
                                    b2.Property<Guid>("LocationOpeningHoursLocationEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeOnly?>("CloseTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly?>("OpenTime")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("LocationOpeningHoursLocationEntityId");

                                    b2.ToTable("locations", "Time");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationOpeningHoursLocationEntityId");
                                });

                            b1.OwnsOne("Overtime.Data.Entities.OpeningHours", "Monday", b2 =>
                                {
                                    b2.Property<Guid>("LocationOpeningHoursLocationEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeOnly?>("CloseTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly?>("OpenTime")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("LocationOpeningHoursLocationEntityId");

                                    b2.ToTable("locations", "Time");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationOpeningHoursLocationEntityId");
                                });

                            b1.OwnsOne("Overtime.Data.Entities.OpeningHours", "Saturday", b2 =>
                                {
                                    b2.Property<Guid>("LocationOpeningHoursLocationEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeOnly?>("CloseTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly?>("OpenTime")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("LocationOpeningHoursLocationEntityId");

                                    b2.ToTable("locations", "Time");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationOpeningHoursLocationEntityId");
                                });

                            b1.OwnsOne("Overtime.Data.Entities.OpeningHours", "Sunday", b2 =>
                                {
                                    b2.Property<Guid>("LocationOpeningHoursLocationEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeOnly?>("CloseTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly?>("OpenTime")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("LocationOpeningHoursLocationEntityId");

                                    b2.ToTable("locations", "Time");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationOpeningHoursLocationEntityId");
                                });

                            b1.OwnsOne("Overtime.Data.Entities.OpeningHours", "Thursday", b2 =>
                                {
                                    b2.Property<Guid>("LocationOpeningHoursLocationEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeOnly?>("CloseTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly?>("OpenTime")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("LocationOpeningHoursLocationEntityId");

                                    b2.ToTable("locations", "Time");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationOpeningHoursLocationEntityId");
                                });

                            b1.OwnsOne("Overtime.Data.Entities.OpeningHours", "Tuesday", b2 =>
                                {
                                    b2.Property<Guid>("LocationOpeningHoursLocationEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeOnly?>("CloseTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly?>("OpenTime")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("LocationOpeningHoursLocationEntityId");

                                    b2.ToTable("locations", "Time");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationOpeningHoursLocationEntityId");
                                });

                            b1.OwnsOne("Overtime.Data.Entities.OpeningHours", "Wednesday", b2 =>
                                {
                                    b2.Property<Guid>("LocationOpeningHoursLocationEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeOnly?>("CloseTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly?>("OpenTime")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("LocationOpeningHoursLocationEntityId");

                                    b2.ToTable("locations", "Time");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationOpeningHoursLocationEntityId");
                                });

                            b1.Navigation("Friday");

                            b1.Navigation("Monday");

                            b1.Navigation("Saturday");

                            b1.Navigation("Sunday");

                            b1.Navigation("Thursday");

                            b1.Navigation("Tuesday");

                            b1.Navigation("Wednesday");
                        });

                    b.Navigation("OpeningHours");
                });

            modelBuilder.Entity("Overtime.Data.Entities.UserEntity", b =>
                {
                    b.HasOne("Overtime.Data.Entities.LocationEntity", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
