// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Overtime.Data;

#nullable disable

namespace overtime.Migrations
{
    [DbContext(typeof(OvertimeDbContext))]
    [Migration("20260608085238_AddUserWorkingTimes")]
    partial class AddUserWorkingTimes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Time")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Overtime.Data.Entities.BookingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BookingRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("booking_ref");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_phone");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("SlotDate")
                        .HasColumnType("date")
                        .HasColumnName("slot_date");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("BookingRef")
                        .IsUnique();

                    b.HasIndex("StaffId", "SlotDate", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("uq_staff_slot");

                    b.ToTable("bookings", "Time");
                });

            modelBuilder.Entity("Overtime.Data.Entities.LocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("locations", "Time");
                });

            modelBuilder.Entity("Overtime.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", "Time");
                });

            modelBuilder.Entity("Overtime.Data.Entities.BookingEntity", b =>
                {
                    b.HasOne("Overtime.Data.Entities.UserEntity", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Overtime.Data.Entities.LocationEntity", b =>
                {
                    b.OwnsOne("Overtime.Data.Entities.LocationOpeningHours", "OpeningHours", b1 =>
                        {
                            b1.Property<Guid>("LocationEntityId")
                                .HasColumnType("uuid");

                            b1.HasKey("LocationEntityId");

                            b1.ToTable("locations", "Time");

                            b1.ToJson("opening_hours");

                            b1.WithOwner()
                                .HasForeignKey("LocationEntityId");

                            b1.OwnsOne("Overtime.Data.Entities.OpeningHours", "Friday", b2 =>
                                {
                                    b2.Property<Guid>("LocationOpeningHoursLocationEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeOnly?>("CloseTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly?>("OpenTime")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("LocationOpeningHoursLocationEntityId");

                                    b2.ToTable("locations", "Time");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationOpeningHoursLocationEntityId");
                                });

                            b1.OwnsOne("Overtime.Data.Entities.OpeningHours", "Monday", b2 =>
                                {
                                    b2.Property<Guid>("LocationOpeningHoursLocationEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeOnly?>("CloseTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly?>("OpenTime")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("LocationOpeningHoursLocationEntityId");

                                    b2.ToTable("locations", "Time");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationOpeningHoursLocationEntityId");
                                });

                            b1.OwnsOne("Overtime.Data.Entities.OpeningHours", "Saturday", b2 =>
                                {
                                    b2.Property<Guid>("LocationOpeningHoursLocationEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeOnly?>("CloseTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly?>("OpenTime")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("LocationOpeningHoursLocationEntityId");

                                    b2.ToTable("locations", "Time");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationOpeningHoursLocationEntityId");
                                });

                            b1.OwnsOne("Overtime.Data.Entities.OpeningHours", "Sunday", b2 =>
                                {
                                    b2.Property<Guid>("LocationOpeningHoursLocationEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeOnly?>("CloseTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly?>("OpenTime")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("LocationOpeningHoursLocationEntityId");

                                    b2.ToTable("locations", "Time");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationOpeningHoursLocationEntityId");
                                });

                            b1.OwnsOne("Overtime.Data.Entities.OpeningHours", "Thursday", b2 =>
                                {
                                    b2.Property<Guid>("LocationOpeningHoursLocationEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeOnly?>("CloseTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly?>("OpenTime")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("LocationOpeningHoursLocationEntityId");

                                    b2.ToTable("locations", "Time");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationOpeningHoursLocationEntityId");
                                });

                            b1.OwnsOne("Overtime.Data.Entities.OpeningHours", "Tuesday", b2 =>
                                {
                                    b2.Property<Guid>("LocationOpeningHoursLocationEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeOnly?>("CloseTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly?>("OpenTime")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("LocationOpeningHoursLocationEntityId");

                                    b2.ToTable("locations", "Time");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationOpeningHoursLocationEntityId");
                                });

                            b1.OwnsOne("Overtime.Data.Entities.OpeningHours", "Wednesday", b2 =>
                                {
                                    b2.Property<Guid>("LocationOpeningHoursLocationEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeOnly?>("CloseTime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly?>("OpenTime")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("LocationOpeningHoursLocationEntityId");

                                    b2.ToTable("locations", "Time");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationOpeningHoursLocationEntityId");
                                });

                            b1.Navigation("Friday");

                            b1.Navigation("Monday");

                            b1.Navigation("Saturday");

                            b1.Navigation("Sunday");

                            b1.Navigation("Thursday");

                            b1.Navigation("Tuesday");

                            b1.Navigation("Wednesday");
                        });

                    b.Navigation("OpeningHours");
                });

            modelBuilder.Entity("Overtime.Data.Entities.UserEntity", b =>
                {
                    b.HasOne("Overtime.Data.Entities.LocationEntity", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.OwnsMany("Overtime.Data.Entities.UserWorkingTime", "WorkingTimes", b1 =>
                        {
                            b1.Property<Guid>("UserEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Day")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<TimeOnly>("ShiftEnd")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly>("ShiftStart")
                                .HasColumnType("time without time zone");

                            b1.HasKey("UserEntityId", "Id");

                            b1.ToTable("users", "Time");

                            b1.ToJson("working_times");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId");
                        });

                    b.Navigation("Location");

                    b.Navigation("WorkingTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
